project_id = "evvzuyxcghokjwhhfwra"

[functions.get-contract-config]
verify_jwt = false

[functions.manifesto-sign]
verify_jwt = false

[functions.manifesto-verify]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.gdpr-delete-user-data]
verify_jwt = true